// Real, legitimate RSS news feeds by country.
// These are official/published RSS feeds from established news organizations.
// Format: { name, url (homepage), country_code, language, category, feed_url, logo }
module.exports = [
  // --- North America ---
  { name: "BBC News", url: "https://www.bbc.com/news", country_code: "GB", language: "en", category: "world", feed_url: "http://feeds.bbci.co.uk/news/world/rss.xml" },
  { name: "BBC Top Stories", url: "https://www.bbc.com/news", country_code: "GB", language: "en", category: "breaking", feed_url: "http://feeds.bbci.co.uk/news/rss.xml" },
  { name: "BBC Politics", url: "https://www.bbc.com/news/politics", country_code: "GB", language: "en", category: "politics", feed_url: "http://feeds.bbci.co.uk/news/politics/rss.xml" },
  { name: "BBC Business", url: "https://www.bbc.com/news/business", country_code: "GB", language: "en", category: "business", feed_url: "http://feeds.bbci.co.uk/news/business/rss.xml" },
  { name: "BBC Technology", url: "https://www.bbc.com/news/technology", country_code: "GB", language: "en", category: "technology", feed_url: "http://feeds.bbci.co.uk/news/technology/rss.xml" },
  { name: "BBC Science & Environment", url: "https://www.bbc.com/news/science_and_environment", country_code: "GB", language: "en", category: "science", feed_url: "http://feeds.bbci.co.uk/news/science_and_environment/rss.xml" },
  { name: "BBC Health", url: "https://www.bbc.com/news/health", country_code: "GB", language: "en", category: "health", feed_url: "http://feeds.bbci.co.uk/news/health/rss.xml" },
  { name: "BBC Entertainment & Arts", url: "https://www.bbc.com/news/entertainment_and_arts", country_code: "GB", language: "en", category: "entertainment", feed_url: "http://feeds.bbci.co.uk/news/entertainment_and_arts/rss.xml" },
  { name: "BBC Sport", url: "https://www.bbc.com/sport", country_code: "GB", language: "en", category: "sports", feed_url: "http://feeds.bbci.co.uk/sport/rss.xml" },
  { name: "The Guardian", url: "https://www.theguardian.com", country_code: "GB", language: "en", category: "world", feed_url: "https://www.theguardian.com/world/rss" },
  { name: "The Guardian Technology", url: "https://www.theguardian.com/uk/technology", country_code: "GB", language: "en", category: "technology", feed_url: "https://www.theguardian.com/technology/rss" },
  { name: "The Guardian Business", url: "https://www.theguardian.com/uk/business", country_code: "GB", language: "en", category: "business", feed_url: "https://www.theguardian.com/uk/business/rss" },
  { name: "The Guardian Football", url: "https://www.theguardian.com/football", country_code: "GB", language: "en", category: "sports", feed_url: "https://www.theguardian.com/football/rss" },
  { name: "The Telegraph World", url: "https://www.telegraph.co.uk/world-news/", country_code: "GB", language: "en", category: "world", feed_url: "https://www.telegraph.co.uk/world-news/rss.xml" },
  { name: "The Times", url: "https://www.thetimes.co.uk", country_code: "GB", language: "en", category: "world", feed_url: "https://www.thetimes.co.uk/newsfeeds/rss/home-page.xml" },
  { name: "Sky News", url: "https://news.sky.com", country_code: "GB", language: "en", category: "world", feed_url: "https://feeds.skynews.com/feeds/rss/home.xml" },
  { name: "CNN Top Stories", url: "https://www.cnn.com", country_code: "US", language: "en", category: "world", feed_url: "http://rss.cnn.com/rss/cnn_topstories.rss" },
  { name: "CNN World", url: "https://www.cnn.com/world", country_code: "US", language: "en", category: "world", feed_url: "http://rss.cnn.com/rss/cnn_world.rss" },
  { name: "CNN Politics", url: "https://www.cnn.com/politics", country_code: "US", language: "en", category: "politics", feed_url: "http://rss.cnn.com/rss/cnn_politics.rss" },
  { name: "CNN Business", url: "https://www.cnn.com/business", country_code: "US", language: "en", category: "business", feed_url: "http://rss.cnn.com/rss/money_latest.rss" },
  { name: "CNN Technology", url: "https://www.cnn.com/tech", country_code: "US", language: "en", category: "technology", feed_url: "http://rss.cnn.com/rss/cnn_tech.rss" },
  { name: "CNN Health", url: "https://www.cnn.com/health", country_code: "US", language: "en", category: "health", feed_url: "http://rss.cnn.com/rss/cnn_health.rss" },
  { name: "CNN Sports", url: "https://www.cnn.com/sport", country_code: "US", language: "en", category: "sports", feed_url: "http://rss.cnn.com/rss/cnn_latest.rss" },
  { name: "Reuters", url: "https://www.reuters.com", country_code: "US", language: "en", category: "world", feed_url: "https://feeds.reuters.com/reuters/topNews" },
  { name: "AP Top News", url: "https://apnews.com", country_code: "US", language: "en", category: "world", feed_url: "https://feed.informer.com/widgets/RSSGF.php?=10311" },
  { name: "NPR News", url: "https://www.npr.org", country_code: "US", language: "en", category: "world", feed_url: "https://feeds.npr.org/1001/rss.xml" },
  { name: "NPR World", url: "https://www.npr.org/sections/world", country_code: "US", language: "en", category: "world", feed_url: "https://feeds.npr.org/1004/rss.xml" },
  { name: "NPR Politics", url: "https://www.npr.org/sections/politics", country_code: "US", language: "en", category: "politics", feed_url: "https://feeds.npr.org/1014/rss.xml" },
  { name: "NPR Business", url: "https://www.npr.org/sections/business", country_code: "US", language: "en", category: "business", feed_url: "https://feeds.npr.org/1006/rss.xml" },
  { name: "NPR Entertainment", url: "https://www.npr.org/sections/entertainment-arts", country_code: "US", language: "en", category: "entertainment", feed_url: "https://feeds.npr.org/1008/rss.xml" },
  { name: "NPR Sports", url: "https://www.npr.org/sections/sports", country_code: "US", language: "en", category: "sports", feed_url: "https://feeds.npr.org/1055/rss.xml" },
  { name: "NPR Health", url: "https://www.npr.org/sections/health", country_code: "US", language: "en", category: "health", feed_url: "https://feeds.npr.org/1128/rss.xml" },
  { name: "NPR Science", url: "https://www.npr.org/sections/science", country_code: "US", language: "en", category: "science", feed_url: "https://feeds.npr.org/1007/rss.xml" },
  { name: "NPR Environment", url: "https://www.npr.org/sections/climate", country_code: "US", language: "en", category: "environment", feed_url: "https://feeds.npr.org/1025/rss.xml" },
  { name: "CBS News", url: "https://www.cbsnews.com", country_code: "US", language: "en", category: "world", feed_url: "https://www.cbsnews.com/latest/rss/main" },
  { name: "ABC News", url: "https://abcnews.go.com", country_code: "US", language: "en", category: "world", feed_url: "https://feeds.abcnews.com/abcnews/topstories" },
  { name: "The Verge", url: "https://www.theverge.com", country_code: "US", language: "en", category: "technology", feed_url: "https://www.theverge.com/rss/index.xml" },
  { name: "Wired", url: "https://www.wired.com", country_code: "US", language: "en", category: "technology", feed_url: "https://www.wired.com/feed/rss" },
  { name: "TechCrunch", url: "https://techcrunch.com", country_code: "US", language: "en", category: "technology", feed_url: "https://techcrunch.com/feed/" },
  { name: "The New York Times World", url: "https://www.nytimes.com", country_code: "US", language: "en", category: "world", feed_url: "https://rss.nytimes.com/services/xml/rss/nyt/World.xml" },
  { name: "The New York Times Business", url: "https://www.nytimes.com/section/business", country_code: "US", language: "en", category: "business", feed_url: "https://rss.nytimes.com/services/xml/rss/nyt/Business.xml" },
  { name: "The New York Times Technology", url: "https://www.nytimes.com/section/technology", country_code: "US", language: "en", category: "technology", feed_url: "https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml" },
  { name: "The New York Times Health", url: "https://www.nytimes.com", country_code: "US", language: "en", category: "health", feed_url: "https://rss.nytimes.com/services/xml/rss/nyt/Health.xml" },
  { name: "The New York Times Science", url: "https://www.nytimes.com/section/science", country_code: "US", language: "en", category: "science", feed_url: "https://rss.nytimes.com/services/xml/rss/nyt/Science.xml" },
  { name: "The New York Times Sports", url: "https://www.nytimes.com/section/sports", country_code: "US", language: "en", category: "sports", feed_url: "https://rss.nytimes.com/services/xml/rss/nyt/Sports.xml" },
  { name: "ESPN", url: "https://www.espn.com", country_code: "US", language: "en", category: "sports", feed_url: "https://www.espn.com/espn/rss/news" },
  { name: "USA Today", url: "https://www.usatoday.com", country_code: "US", language: "en", category: "world", feed_url: "https://www.usatoday.com/arc/outboundfeeds/rss/?outputType=xml" },
  { name: "Time Magazine", url: "https://time.com", country_code: "US", language: "en", category: "world", feed_url: "https://time.com/feed/" },
  { name: "Forbes", url: "https://www.forbes.com", country_code: "US", language: "en", category: "business", feed_url: "https://www.forbes.com/business/feed/" },
  { name: "CNBC", url: "https://www.cnbc.com", country_code: "US", language: "en", category: "finance", feed_url: "https://www.cnbc.com/id/100003114/device/rss/rss.html" },
  { name: "Bloomberg", url: "https://www.bloomberg.com", country_code: "US", language: "en", category: "finance", feed_url: "https://feeds.bloomberg.com/markets/news.rss" },
  { name: "The Washington Post", url: "https://www.washingtonpost.com", country_code: "US", language: "en", category: "world", feed_url: "https://feeds.washingtonpost.com/rss/world" },
  { name: "CBC News", url: "https://www.cbc.ca/news", country_code: "CA", language: "en", category: "world", feed_url: "https://www.cbc.ca/cmlink/rss-topstories" },
  { name: "Global News Canada", url: "https://globalnews.ca", country_code: "CA", language: "en", category: "world", feed_url: "https://globalnews.ca/feed/" },
  { name: "CTV News", url: "https://www.ctvnews.ca", country_code: "CA", language: "en", category: "world", feed_url: "https://www.ctvnews.ca/rss/ctvnews-ca-top-stories-public-rss-1.822009" },
  // --- Europe ---
  { name: "Le Monde", url: "https://www.lemonde.fr", country_code: "FR", language: "fr", category: "world", feed_url: "https://www.lemonde.fr/rss/une.xml" },
  { name: "France 24", url: "https://www.france24.com", country_code: "FR", language: "en", category: "world", feed_url: "https://www.france24.com/en/rss" },
  { name: "RFI English", url: "https://www.rfi.fr/en/", country_code: "FR", language: "en", category: "world", feed_url: "https://www.rfi.fr/en/rss" },
  { name: "Le Figaro", url: "https://www.lefigaro.fr", country_code: "FR", language: "fr", category: "world", feed_url: "https://www.lefigaro.fr/rss/figaro_actualite.xml" },
  { name: "Der Spiegel", url: "https://www.spiegel.de", country_code: "DE", language: "de", category: "world", feed_url: "https://www.spiegel.de/schlagzeilen/tops/index.rss" },
  { name: "DW (Deutsche Welle)", url: "https://www.dw.com", country_code: "DE", language: "en", category: "world", feed_url: "https://rss.dw.com/rdf/rss-en-all" },
  { name: "Die Zeit", url: "https://www.zeit.de", country_code: "DE", language: "de", category: "world", feed_url: "https://newsfeed.zeit.de/index" },
  { name: "FAZ", url: "https://www.faz.net", country_code: "DE", language: "de", category: "world", feed_url: "https://www.faz.net/rss/aktuell/" },
  { name: "Corriere della Sera", url: "https://www.corriere.it", country_code: "IT", language: "it", category: "world", feed_url: "https://www.corriere.it/rss/english.xml" },
  { name: "La Repubblica", url: "https://www.repubblica.it", country_code: "IT", language: "it", category: "world", feed_url: "https://www.repubblica.it/rss/homepage/rss2.0.xml" },
  { name: "ANSA Italy", url: "https://www.ansa.it", country_code: "IT", language: "en", category: "world", feed_url: "https://www.ansa.it/english/englishnews.xml" },
  { name: "El País", url: "https://elpais.com", country_code: "ES", language: "es", category: "world", feed_url: "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada" },
  { name: "RTVE Spain", url: "https://www.rtve.es", country_code: "ES", language: "es", category: "world", feed_url: "https://www.rtve.es/api/noticias/feed/rss.xml" },
  { name: "Publico Portugal", url: "https://www.publico.pt", country_code: "PT", language: "pt", category: "world", feed_url: "https://feeds.feedburner.com/PublicoRSS" },
  { name: "NOS Netherlands", url: "https://nos.nl", country_code: "NL", language: "nl", category: "world", feed_url: "https://feeds.nos.nl/nosnieuwsalgemeen" },
  { name: "NPO Netherlands", url: "https://www.npostart.nl", country_code: "NL", language: "nl", category: "world", feed_url: "https://nos.nl/nieuws/algemeen/rss" },
  { name: "VRT Belgium", url: "https://www.vrt.be", country_code: "BE", language: "nl", category: "world", feed_url: "https://www.vrt.be/vrtnws/nl.rss.articles.xml" },
  { name: "SRF Switzerland", url: "https://www.srf.ch", country_code: "CH", language: "de", category: "world", feed_url: "https://www.srf.ch/news/bundesrat/rss/1890" },
  { name: "Schweizer Radio DRS", url: "https://www.srf.ch/news", country_code: "CH", language: "de", category: "world", feed_url: "https://www.srf.ch/news/rss/1890" },
  { name: "Der Standard Austria", url: "https://www.derstandard.at", country_code: "AT", language: "de", category: "world", feed_url: "https://www.derstandard.at/rss" },
  { name: "DR Denmark", url: "https://www.dr.dk", country_code: "DK", language: "da", category: "world", feed_url: "https://www.dr.dk/rss/allenyheder" },
  { name: "NRK Norway", url: "https://www.nrk.no", country_code: "NO", language: "no", category: "world", feed_url: "https://www.nrk.no/toppsaker.rss" },
  { name: "Aftonbladet Sweden", url: "https://www.aftonbladet.se", country_code: "SE", language: "sv", category: "world", feed_url: "https://rss.aftonbladet.se/rss2/small/toppnyheter/" },
  { name: "YLE Finland", url: "https://yle.fi", country_code: "FI", language: "fi", category: "world", feed_url: "https://feeds.yle.fi/uutiset/v1/majorHeadlines/YLE_UUTISET.rss" },
  { name: "RÚV Iceland", url: "https://www.ruv.is", country_code: "IS", language: "is", category: "world", feed_url: "https://www.ruv.is/rss" },
  { name: "Onet Poland", url: "https://www.onet.pl", country_code: "PL", language: "pl", category: "world", feed_url: "https://wiadomosci.onet.pl/.feed" },
  { name: "TVN24 Poland", url: "https://tvn24.pl", country_code: "PL", language: "pl", category: "world", feed_url: "https://tvn24.pl/najnowsze.xml" },
  { name: "ČT24 Czech", url: "https://ct24.ceskatelevize.cz", country_code: "CZ", language: "cs", category: "world", feed_url: "https://ct24.ceskatelevize.cz/rss/zpravy" },
  { name: "aktualne.cz", url: "https://zpravy.aktualne.cz", country_code: "CZ", language: "cs", category: "world", feed_url: "https://zpravy.aktualne.cz/rss/" },
  { name: "ČTK Czech", url: "https://www.ceskenoviny.cz", country_code: "CZ", language: "cs", category: "world", feed_url: "https://www.ceskenoviny.cz/sluzby/rss_cn.php" },
  { name: "SME Slovakia", url: "https://www.sme.sk", country_code: "SK", language: "sk", category: "world", feed_url: "https://www.sme.sk/rss-title/rss.xml" },
  { name: "Aktuality.sk", url: "https://www.aktuality.sk", country_code: "SK", language: "sk", category: "world", feed_url: "https://www.aktuality.sk/rss/" },
  { name: "Denník N", url: "https://dennikn.sk", country_code: "SK", language: "sk", category: "world", feed_url: "https://dennikn.sk/feed/" },
  { name: "Hospodárske noviny", url: "https://hnonline.sk", country_code: "SK", language: "sk", category: "business", feed_url: "https://hnonline.sk/rss" },
  { name: "SITA Slovakia", url: "https://www.sita.sk", country_code: "SK", language: "sk", category: "world", feed_url: "https://www.sita.sk/feed/" },
  { name: "origo Hungary", url: "https://www.origo.hu", country_code: "HU", language: "hu", category: "world", feed_url: "https://www.origo.hu/content/rss/origo.xml" },
  { name: "Mediafax Romania", url: "https://www.mediafax.ro", country_code: "RO", language: "ro", category: "world", feed_url: "https://www.mediafax.ro/rss" },
  { name: "Dnevnik Bulgaria", url: "https://www.dnevnik.bg", country_code: "BG", language: "bg", category: "world", feed_url: "https://www.dnevnik.bg/rss" },
  { name: "Kathimerini Greece", url: "https://www.kathimerini.gr", country_code: "GR", language: "el", category: "world", feed_url: "https://www.kathimerini.gr/rss/inside/" },
  { name: "HRT Croatia", url: "https://vijesti.hrt.hr", country_code: "HR", language: "hr", category: "world", feed_url: "https://vijesti.hrt.hr/rss" },
  { name: "RTV Slovenia", url: "https://www.rtvslo.si", country_code: "SI", language: "sl", category: "world", feed_url: "https://www.rtvslo.si/get_feed.php" },
  { name: "Danas Serbia", url: "https://www.danas.rs", country_code: "RS", language: "sr", category: "world", feed_url: "https://www.danas.rs/feed/" },
  { name: "Radio Ukraine", url: "https://www.radiosvoboda.org", country_code: "UA", language: "uk", category: "world", feed_url: "https://www.radiosvoboda.org/api/zprqvicitjt" },
  { name: "Unian Ukraine", url: "https://www.unian.ua", country_code: "UA", language: "uk", category: "world", feed_url: "https://www.unian.ua/rss" },
  { name: "Ukrinform Ukraine", url: "https://www.ukrinform.net", country_code: "UA", language: "en", category: "world", feed_url: "https://www.ukrinform.net/rss/block-lastnews" },
  { name: "TASS Russia", url: "https://tass.com", country_code: "RU", language: "en", category: "world", feed_url: "https://tass.com/rss/v2.xml" },
  { name: "Sputnik", url: "https://sputniknews.com", country_code: "RU", language: "en", category: "world", feed_url: "https://sputniknews.com/export/rss2/archive/index.xml" },
  { name: "BelTA Belarus", url: "https://eng.belta.by", country_code: "BY", language: "en", category: "world", feed_url: "https://eng.belta.by/rss" },
  { name: "Mortgage Express Latvia", url: "https://eng.lsm.lv", country_code: "LV", language: "en", category: "world", feed_url: "https://eng.lsm.lv/rss/lang/eng/" },
  { name: "Delfi Estonia", url: "https://news.err.ee", country_code: "EE", language: "en", category: "world", feed_url: "https://news.err.ee/rss" },
  { name: "LRT Lithuania", url: "https://www.lrt.lt", country_code: "LT", language: "en", category: "world", feed_url: "https://www.lrt.lt/feeds/4538" },
  // --- Americas (South + Latin) ---
  { name: "Folha de S.Paulo", url: "https://www.folha.uol.com.br", country_code: "BR", language: "pt", category: "world", feed_url: "https://feeds.folha.uol.com.br/feed/feed.xml" },
  { name: "O Globo Brazil", url: "https://oglobo.globo.com", country_code: "BR", language: "pt", category: "world", feed_url: "https://oglobo.globo.com/rss.xml" },
  { name: "UOL Noticias", url: "https://noticias.uol.com.br", country_code: "BR", language: "pt", category: "world", feed_url: "https://rss.noticias.uol.com.br/feeds/ultimas-noticias.xml" },
  { name: "Clarín Argentina", url: "https://www.clarin.com", country_code: "AR", language: "es", category: "world", feed_url: "https://www.clarin.com/rss/lo-ultimo/" },
  { name: "La Nación Argentina", url: "https://www.lanacion.com.ar", country_code: "AR", language: "es", category: "world", feed_url: "https://www.lanacion.com.ar/arc/outboundfeeds/rss/?outputType=xml" },
  { name: "Emol Chile", url: "https://www.emol.com", country_code: "CL", language: "es", category: "world", feed_url: "https://www.emol.com/rss/portada.xml" },
  { name: "El Tiempo Colombia", url: "https://www.eltiempo.com", country_code: "CO", language: "es", category: "world", feed_url: "https://www.eltiempo.com/rss/colombia_0.xml" },
  { name: "El Comercio Peru", url: "https://elcomercio.pe", country_code: "PE", language: "es", category: "world", feed_url: "https://elcomercio.pe/arc/outboundfeeds/rss/" },
  { name: "El Universal Mexico", url: "https://www.eluniversal.com.mx", country_code: "MX", language: "es", category: "world", feed_url: "https://www.eluniversal.com.mx/rss/" },
  { name: "El Universal Venezuela", url: "https://www.eluniversal.com", country_code: "VE", language: "es", category: "world", feed_url: "https://www.eluniversal.com/rss/titulares/" },
  { name: "El País Uruguay", url: "https://www.elpais.com.uy", country_code: "UY", language: "es", category: "world", feed_url: "https://www.elpais.com.uy/rss" },
  // --- Asia ---
  { name: "NHK World Japan", url: "https://www3.nhk.or.jp/nhkworld/en/news/", country_code: "JP", language: "en", category: "world", feed_url: "https://www3.nhk.or.jp/rss/news/cat0.xml" },
  { name: "Kyodo News Japan", url: "https://english.kyodonews.net", country_code: "JP", language: "en", category: "world", feed_url: "https://english.kyodonews.net/rss/all.xml" },
  { name: "Asahi Japan", url: "https://www.asahi.com", country_code: "JP", language: "ja", category: "world", feed_url: "https://www.asahi.com/rss/asahi/newsheadlines.rdf" },
  { name: "Yomiuri Japan", url: "https://www.yomiuri.co.jp", country_code: "JP", language: "ja", category: "world", feed_url: "https://www.yomiuri.co.jp/news/feed/" },
  { name: "India Today", url: "https://www.indiatoday.in", country_code: "IN", language: "en", category: "world", feed_url: "https://www.indiatoday.in/rss/1206578" },
  { name: "The Hindu India", url: "https://www.thehindu.com", country_code: "IN", language: "en", category: "world", feed_url: "https://www.thehindu.com/feeder/default.rss" },
  { name: "Hindustan Times", url: "https://www.hindustantimes.com", country_code: "IN", language: "en", category: "world", feed_url: "https://www.hindustantimes.com/feeds/rss/top-news/rssfeed.xml" },
  { name: "Times of India", url: "https://timesofindia.indiatimes.com", country_code: "IN", language: "en", category: "world", feed_url: "https://timesofindia.indiatimes.com/rssfeeds/296589292.cms" },
  { name: "China Daily", url: "https://www.chinadaily.com.cn", country_code: "CN", language: "en", category: "world", feed_url: "https://www.chinadaily.com.cn/rss/china_rss.xml" },
  { name: "China Xinhua", url: "http://www.xinhuanet.com/english", country_code: "CN", language: "en", category: "world", feed_url: "http://www.chinadaily.com.cn/rss/world_rss.xml" },
  { name: "Korea Herald", url: "http://www.koreaherald.com", country_code: "KR", language: "en", category: "world", feed_url: "http://www.koreaherald.com/rss/1" },
  { name: "Arirang South Korea", url: "http://www.arirang.co.kr", country_code: "KR", language: "en", category: "world", feed_url: "http://www.arirang.co.kr/News/News_List_Rss.asp" },
  { name: "Taipei Times", url: "http://www.taipeitimes.com", country_code: "TW", language: "en", category: "world", feed_url: "http://www.taipeitimes.com/xmlrss/rss.xml" },
  { name: "Straits Times Singapore", url: "https://www.straitstimes.com", country_code: "SG", language: "en", category: "world", feed_url: "https://www.straitstimes.com/news/singapore/rss.xml" },
  { name: "Bangkok Post", url: "https://www.bangkokpost.com", country_code: "TH", language: "en", category: "world", feed_url: "https://www.bangkokpost.com/rss/world.xml" },
  { name: "The Star Malaysia", url: "https://www.thestar.com.my", country_code: "MY", language: "en", category: "world", feed_url: "https://www.thestar.com.my/rss/News/Nation" },
  { name: "Vietnam News", url: "https://vietnamnews.vn", country_code: "VN", language: "en", category: "world", feed_url: "https://vietnamnews.vn/rss/world.rss" },
  { name: "The Philippine Star", url: "https://www.philstar.com", country_code: "PH", language: "en", category: "world", feed_url: "https://www.philstar.com/rss/world?l=1340380451" },
  { name: "Jakarta Globe", url: "https://jakartaglobe.id", country_code: "ID", language: "en", category: "world", feed_url: "https://jakartaglobe.id/feed" },
  { name: "The Jakarta Post", url: "https://www.thejakartapost.com", country_code: "ID", language: "en", category: "world", feed_url: "https://www.thejakartapost.com/rss.xml" },
  { name: "Dawn Pakistan", url: "https://www.dawn.com", country_code: "PK", language: "en", category: "world", feed_url: "https://www.dawn.com/feeds/home" },
  { name: "The Daily Star Bangladesh", url: "https://www.thedailystar.net", country_code: "BD", language: "en", category: "world", feed_url: "https://www.thedailystar.net/frontpage/rss.xml" },
  { name: "Arab News", url: "https://www.arabnews.com", country_code: "SA", language: "en", category: "world", feed_url: "https://www.arabnews.com/rss" },
  { name: "Gulf News", url: "https://gulfnews.com", country_code: "AE", language: "en", category: "world", feed_url: "https://gulfnews.com/rss" },
  { name: "Khaleej Times", url: "https://www.khaleejtimes.com", country_code: "AE", language: "en", category: "world", feed_url: "https://www.khaleejtimes.com/rss-section/1" },
  { name: "The National UAE", url: "https://www.thenationalnews.com", country_code: "AE", language: "en", category: "world", feed_url: "https://www.thenationalnews.com/arc/outboundfeeds/rss/?outputType=xml" },
  { name: "The Jerusalem Post", url: "https://www.jpost.com", country_code: "IL", language: "en", category: "world", feed_url: "https://www.jpost.com/Rss/RssFeedsIsrael.aspx" },
  { name: "HAARETZ", url: "https://www.haaretz.com", country_code: "IL", language: "en", category: "world", feed_url: "https://www.haaretz.com/cmlink/1.628539" },
  { name: "Anadolu Agency Turkey", url: "https://www.aa.com.tr", country_code: "TR", language: "en", category: "world", feed_url: "https://www.aa.com.tr/en/rss/default?cat=guncel" },
  { name: "Hurriyet Daily News", url: "https://www.hurriyetdailynews.com", country_code: "TR", language: "en", category: "world", feed_url: "https://www.hurriyetdailynews.com/rss.aspx" },
  // --- Oceania ---
  { name: "ABC News Australia", url: "https://www.abc.net.au/news", country_code: "AU", language: "en", category: "world", feed_url: "https://www.abc.net.au/news/feed/2942460/rss.xml" },
  { name: "ABC News Australia Top Stories", url: "https://www.abc.net.au/news", country_code: "AU", language: "en", category: "breaking", feed_url: "https://www.abc.net.au/news/feed/2942460/rss.xml" },
  { name: "ABC Australia World", url: "https://www.abc.net.au/news/world", country_code: "AU", language: "en", category: "world", feed_url: "https://www.abc.net.au/news/feed/83640/rss.xml" },
  { name: "ABC Australia Business", url: "https://www.abc.net.au/news/business", country_code: "AU", language: "en", category: "business", feed_url: "https://www.abc.net.au/news/feed/8664/rss.xml" },
  { name: "ABC Australia Sport", url: "https://www.abc.net.au/news/sport", country_code: "AU", language: "en", category: "sports", feed_url: "https://www.abc.net.au/news/feed/45918/rss.xml" },
  { name: "The Sydney Morning Herald", url: "https://www.smh.com.au", country_code: "AU", language: "en", category: "world", feed_url: "https://www.smh.com.au/rss/feed/world.xml" },
  { name: "Stuff New Zealand", url: "https://www.stuff.co.nz", country_code: "NZ", language: "en", category: "world", feed_url: "https://www.stuff.co.nz/rss/" },
  { name: "NZ Herald", url: "https://www.nzherald.co.nz", country_code: "NZ", language: "en", category: "world", feed_url: "https://www.nzherald.co.nz/rss/" },
  // --- Africa ---
  { name: "Premium Times Nigeria", url: "https://www.premiumtimesng.com", country_code: "NG", language: "en", category: "world", feed_url: "https://www.premiumtimesng.com/feed" },
  { name: "Punch Nigeria", url: "https://punchng.com", country_code: "NG", language: "en", category: "world", feed_url: "https://punchng.com/feed/" },
  { name: "Vanguard Nigeria", url: "https://www.vanguardngr.com", country_code: "NG", language: "en", category: "world", feed_url: "https://www.vanguardngr.com/feed/" },
  { name: "Daily Nation Kenya", url: "https://nation.africa/kenya", country_code: "KE", language: "en", category: "world", feed_url: "https://nation.africa/kenya/nation/-/feed/rss" },
  { name: "Citizen Digital Kenya", url: "https://citizen.digital", country_code: "KE", language: "en", category: "world", feed_url: "https://citizen.digital/feed" },
  { name: "AllAfrica", url: "https://allafrica.com", country_code: "ZA", language: "en", category: "world", feed_url: "https://allafrica.com/tools/headlines/rdf/latest/headlines.rdf" },
  { name: "The Namibian", url: "https://www.namibian.com.na", country_code: "NA", language: "en", category: "world", feed_url: "https://www.namibian.com.na/feed/" },
  { name: "Egypt Today", url: "https://www.egypttoday.com", country_code: "EG", language: "en", category: "world", feed_url: "https://www.egypttoday.com/rss/news.xml" },
  { name: "Ahram Online Egypt", url: "https://english.ahram.org.eg", country_code: "EG", language: "en", category: "world", feed_url: "https://english.ahram.org.eg/RSS/rss.aspx?NewsType=12" },
  { name: "Daily Maverick South Africa", url: "https://www.dailymaverick.co.za", country_code: "ZA", language: "en", category: "world", feed_url: "https://www.dailymaverick.co.za/feed/" },
  { name: "GhanaWeb", url: "https://www.ghanaweb.com", country_code: "GH", language: "en", category: "world", feed_url: "https://www.ghanaweb.com/GhanaHomePage/rss/" },
  { name: "The New Times Rwanda", url: "https://www.newtimes.co.rw", country_code: "RW", language: "en", category: "world", feed_url: "https://www.newtimes.co.rw/rss.xml" }
];
